name: $(Date:yyyyMMdd)$(Rev:.rrr)

jobs:
- job: build

  pool:
    name: PowerShell

  steps:
  - powershell: |
      Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    displayName: Install Choco
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: travisez13
      repository: 'travisez13/powershell_build_base'
      Dockerfile: powershell/build/base/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
