name: $(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

jobs:
- job: build

  pool:
    name: PowerShell

  steps:
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: travisez13
      repository: 'travisez13/powershell_build_base'
      Dockerfile: powershell/build/base/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
