name: $(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

jobs:
- job: build_2016

  pool:
    vmImage: vs2017-win2016

  steps:
  - task: Docker@2
    displayName: build
    inputs:
      command: build
      repository: 'travisez13/powershell_build_base'
      Dockerfile: powershell/build/base/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
- job: build_2019

  pool:
    vmImage: windows-2019

  steps:
  - task: Docker@2
    displayName: build
    inputs:
      command: build
      repository: 'travisez13/powershell_build_base2019'
      Dockerfile: powershell/build/2019/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
