name: $(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

jobs:
- template: ./templates/job.yml
  parameters:
    jobName: build_2016_mscodehub
    condition: eq(variables['collection_name'], 'mscodehub')
    poolName: PowerShell

- template: ./templates/job.yml
  parameters:
    jobName: build_2016_hosted
    vmImage: vs2017-win2016

- template: ./templates/job.yml
  parameters:
    jobName: build_2019
    vmImage: windows-2019
    arguments: --build-arg fromTag=ltsc2016
