name: $(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

jobs:
- job: build_2016_mscodehub
  condition: eq(variables['collection_name'], 'mscodehub')

  pool:
    name: PowerShell

  steps:
  - powershell: docker info
    displayName: Get docker info
  - task: Docker@2
    displayName: build
    inputs:
      command: build
      repository: 'travisez13/powershell_build_base'
      Dockerfile: powershell/build/base/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)

- job: build_2016_hosted

  pool:
    vmImage: vs2017-win2016

  steps:
  - powershell: docker info
    displayName: Get docker info
  - task: Docker@2
    displayName: build
    inputs:
      command: build
      repository: 'travisez13/powershell_build_base'
      Dockerfile: powershell/build/base/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
- job: build_2019

  pool:
    vmImage: windows-2019

  steps:
  - powershell: docker info
    displayName: Get docker info
  - task: Docker@2
    displayName: build
    inputs:
      command: build
      repository: 'travisez13/powershell_build_base2019'
      Dockerfile: powershell/build/2019/Dockerfile
      tags: |
        latest
        $(Build.BuildNumber)
